# Generated by Django 5.1.1 on 2024-09-12 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bookTypeName', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '图书类别信息',
                'db_table': 't_bookType',
            },
        ),
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bookName', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('publishDate', models.DateField()),
                ('bookType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Project01.booktype')),
            ],
            options={
                'verbose_name': '图书信息',
                'db_table': 't_book',
            },
        ),
    ]
