# Generated by Django 5.1.1 on 2024-09-13 01:14

import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=20)),
                ('account', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='bookType',
            field=models.ForeignKey(on_delete=django.db.models.query.Prefetch, to='Project01.booktype'),
        ),
    ]
