# Generated by Django 5.1.1 on 2024-09-13 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project01', '0002_accountinfo_alter_bookinfo_booktype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountinfo',
            options={'verbose_name': '用户账户信息'},
        ),
        migrations.AlterModelTable(
            name='accountinfo',
            table='t_account',
        ),
    ]
